run:
  timeout: 10m

linters:
  enable:
    - depguard
    - gofmt
    - goimports
    - revive
    - govet
    - importas
    - ineffassign
    - misspell
    - typecheck
    - errname
    - makezero
    - whitespace
    - unused
  disable-all: true

linters-settings:
  depguard:
    rules:
      main:
        deny:
          # The io/ioutil package has been deprecated.
          # https://go.dev/doc/go1.16#ioutil
          - pkg: "io/ioutil"
            desc: The io/ioutil package has been deprecated.
  importas:
    no-unaliased: true

issues:
  exclude-rules:
    - linters:
        - revive
      text: "stutters"

# show all
max-issues-per-linter: 0
max-same-issues: 0
